In [1]:
import numpy as np

# 1.

a = np.matrix("0.05,0.07,0;0.05,0,0.06;1,1,1")
b = np.matrix("2250;1400;50000")
x = np.linalg.solve(a, b)
print(x)


[[10000.]
 [25000.]
 [15000.]]


In [7]:
import numpy as np

# 2.

a = np.matrix("1,1,1;-1,1,0;1,0,-1")
b = np.matrix("1328;120;100")
x = np.linalg.solve(a, b)
print(x)

[[436.]
 [556.]
 [336.]]


In [9]:
import numpy as np

# 3.

a = np.matrix("0.333333333,0.166666667,1;0,0.25,0.333333333;0.333333333,0,1")
b = np.matrix("1;1;1")
x = np.linalg.solve(a, b)
print(x)


[[-6.00000001]
 [ 0.        ]
 [ 3.        ]]


In [10]:
import numpy as np

# 4.

a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
x = np.linalg.solve(a, b)
print(x)


[[4.]
 [5.]
 [3.]]


In [5]:
import numpy as np

# 5.

def get_polynom(coords):
    n = len(coords) - 1
    a = []
    b = []
    for i in range(n + 1):
        row = []
        for j in range(n + 1):
            row.append(coords[i][0] ** j)
        a.append(row)
        b.append(coords[i][1])
    return np.linalg.solve(a,b)


coords = [(1, 12), (3, 54), (-1, 2)]
print(get_polynom(coords))

[3. 5. 4.]
